CREATE TABLE IF NOT EXISTS support_sessions (
  line_user_id TEXT PRIMARY KEY,
  status TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);